import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { requireOwnerCredentials, projectName } from './deploy-config';
import { ensurePagesProject } from './pages-project';
const {accountId,token}=requireOwnerCredentials(process.env);
const git=(args:string[])=>execFileSync('git',args,{encoding:'utf8'}).trim();
if (git(['status','--porcelain'])) throw new Error('Commit the source before deploying. The build must include the current data history.');
const head=git(['rev-parse','HEAD']);
const build=JSON.parse(readFileSync('dist/build.json','utf8'));
if (build.revision!==head) throw new Error('Build revision does not match HEAD. Run npm run build after committing.');
await ensurePagesProject(accountId,token);
execFileSync(process.execPath,['node_modules/wrangler/bin/wrangler.js','pages','deploy','dist','--project-name',projectName,'--branch','main','--commit-hash',head,'--commit-dirty=false'],{stdio:'inherit',env:{...process.env,CLOUDFLARE_ACCOUNT_ID:accountId,CLOUDFLARE_API_TOKEN:token,WRANGLER_SEND_METRICS:'false'}});
